import {
  UilEstate,
  UilUser,
  UilImage,
  UilEnvelopes,
  UilGithubAlt,
  UilLinkedinAlt,
  UilInstagram,
} from '@iconscout/react-unicons';

const sidebarLinks = [
  {
    id: 1,
    navLink: 'Home',
    navIcon: <UilEstate />,
    toLocation: '/',
    ariaLabel: 'Go to Homepage',
    label: 'Home',
  },
  {
    id: 2,
    navLink: 'About',
    navIcon: <UilUser />,
    toLocation: '/about',
    ariaLabel: 'Go to About page',
    label: 'About',
  },
  {
    id: 3,
    navLink: 'Portfolio',
    navIcon: <UilImage />,
    toLocation: '/portfolio',
    ariaLabel: 'Go to Portfolio page',
    label: 'Portfolio',
  },
  {
    id: 4,
    navLink: 'Contact',
    navIcon: <UilEnvelopes />,
    toLocation: '/contact',
    ariaLabel: 'Go to Contact page',
    label: 'Contact',
  },
];

const sidebarSocial = [
  {
    id: 1,
    navLink: 'GitHub',
    urlLink: 'https://github.com/Danijel00',
    navIcon: <UilGithubAlt />,
  },
  {
    id: 2,
    navLink: 'Linkedin',
    urlLink: 'https://www.linkedin.com/in/danijel-kocic00/',
    navIcon: <UilLinkedinAlt />,
  },
  {
    id: 3,
    navLink: 'Instagram',
    urlLink: 'https://www.instagram.com/danijel_k00',
    navIcon: <UilInstagram />,
  },
];

const aboutCube = [
  {
    id: 1,
    skillLogoImg: '../../src/image/html5.svg',
    class: 'face1',
  },
  {
    id: 2,
    skillLogoImg: '../../src/image/react.svg',
    class: 'face2',
  },
  {
    id: 3,
    skillLogoImg: '../../src/image/css3.svg',
    class: 'face3',
  },
  {
    id: 4,
    skillLogoImg: '../../src/image/sass.svg',
    class: 'face4',
  },
  {
    id: 5,
    skillLogoImg: '../../src/image/javascript.svg',
    class: 'face5',
  },
  {
    id: 6,
    skillLogoImg: '../../src/image/github.svg',
    class: 'face6',
  },
];

const portfolioData = [
  {
    id: 1,
    imgUrl: '../../src/image/restio.gif',
    imgAlt: 'work1',
    title: 'Restio',
    description: 'A Restaurant website',
    technology: 'Built with: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicrestio.netlify.app/',
    github: 'https://github.com/Danijel00/Restaurant-project',
  },

  {
    id: 2,
    imgUrl: '../../src/image/sportstore.gif',
    imgAlt: 'work2',
    title: 'SportStore',
    description: 'A Sport store website',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicsportstore.netlify.app/',
    github: 'https://github.com/Danijel00/Sport-Store-project',
  },
  {
    id: 3,
    imgUrl: '../../src/image/movie-search.gif',
    imgAlt: 'work3',
    title: 'MovieSpace',
    description: 'Search for movies via omdb API',
    technology: 'Technologies used: React and Sass',
    website: 'https://danijel00.github.io/React-movie-search/',
    github: 'https://github.com/Danijel00/React-movie-search',
  },
  {
    id: 4,
    imgUrl: '../../src/image/natours.gif',
    imgAlt: 'work4',
    title: 'Natours',
    description: 'A Traveling agency website',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicnatours.netlify.app/',
    github: 'https://github.com/Danijel00/Natours-project',
  },
  {
    id: 5,
    imgUrl: '../../src/image/github-user-search.gif',
    imgAlt: 'work5',
    title: 'GitHub user search',
    description: 'Search for any GitHub user',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicgithubsearch.netlify.app/',
    github: 'https://github.com/Danijel00/GitHub-user-project',
  },
  {
    id: 6,
    imgUrl: '../../src/image/weather.gif',
    imgAlt: 'work6',
    title: 'Weather search',
    description: "See what's the weather in any city",
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicweather.netlify.app/',
    github: 'https://github.com/Danijel00/Weather-project',
  },
  {
    id: 7,
    imgUrl: '../../src/image/todos.gif',
    imgAlt: 'work7',
    title: 'ToDos',
    description: 'Create todos',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocictodos.netlify.app/',
    github: 'https://github.com/Danijel00/Todos-project',
  },
  {
    id: 8,
    imgUrl: '../../src/image/nexter.gif',
    imgAlt: 'work8',
    title: 'Nexter',
    description: 'RealTours website',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicnexter.netlify.app/',
    github: 'https://github.com/Danijel00/Nexter-project',
  },
  {
    id: 9,
    imgUrl: '../../src/image/deluminal.gif',
    imgAlt: 'work9',
    title: 'Chamber',
    description: 'Project done as a technical test',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicchamber.netlify.app/',
    // github: 'https://github.com/Danijel00/Chamber-project',
  },
  {
    id: 10,
    imgUrl: '../../src/image/valves.gif',
    imgAlt: 'work10',
    title: 'Valves',
    description: 'Project done as a technical test',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: 'https://danijelkocicvalves.netlify.app/',
    // github: 'https://github.com/Danijel00/Valves-project',
  },
  {
    id: 11,
    imgUrl: '../../src/image/dashboard.png',
    imgAlt: 'work11',
    title: 'Admin Dashboard',
    description: 'Project done as a technical test',
    technology: 'Technologies used: HTML/SASS, and JavaScript',
    website: '  https://danijelkocicdashboard.netlify.app/',
    // github: 'https://github.com/Danijel00/Dashboard-project',
  },
];

export { sidebarLinks, sidebarSocial, aboutCube, portfolioData };
